# Generated by Django 4.1.4 on 2022-12-12 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import punkin_patch.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to=punkin_patch.models.user_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatchInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterID1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character1', to='punkin_patch.character')),
                ('characterID2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character2', to='punkin_patch.character')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punkin_patch.patchinstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('winningCharacterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winningCharacter', to='punkin_patch.character')),
            ],
        ),
        migrations.CreateModel(
            name='PatchTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('characters', models.ManyToManyField(to='punkin_patch.character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='patchinstance',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punkin_patch.patchtemplate'),
        ),
        migrations.AddField(
            model_name='patchinstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('characterID1', 'characterID2', 'instance'), name='No duplicate votes in patch instance'),
        ),
    ]
