# Generated by Django 4.1.4 on 2022-12-10 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('punkin_patch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchtemplate',
            name='character',
            field=models.ManyToManyField(limit_choices_to={'user': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)}, to='punkin_patch.character'),
        ),
    ]
