# Generated by Django 4.1.4 on 2022-12-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punkin_patch', '0002_patchtemplate_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patchtemplate',
            name='character',
        ),
        migrations.AddField(
            model_name='patchtemplate',
            name='characters',
            field=models.ManyToManyField(to='punkin_patch.character'),
        ),
    ]
