# Generated by Django 4.1.4 on 2022-12-10 23:07

from django.db import migrations, models
import punkin_patch.models


class Migration(migrations.Migration):

    dependencies = [
        ('punkin_patch', '0003_remove_patchtemplate_character_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(null=True, upload_to=punkin_patch.models.user_directory_path),
        ),
    ]
