# Generated by Django 4.1.4 on 2022-12-10 23:43

from django.db import migrations, models
import punkin_patch.models


class Migration(migrations.Migration):

    dependencies = [
        ('punkin_patch', '0004_character_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, upload_to=punkin_patch.models.user_directory_path),
        ),
    ]
